# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'SGalindoEcommerce' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwipeCellKit'
  pod 'iOSDropDown'
  pod 'RadioButton'
  pod 'FMDB'
  # Pods for SGalindoEcommerce

end
